{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: selenium in c:\\users\\skand\\anaconda3\\lib\\site-packages (4.27.1)\n",
      "Requirement already satisfied: trio~=0.17 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from selenium) (0.27.0)\n",
      "Requirement already satisfied: typing_extensions~=4.9 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from selenium) (4.13.2)\n",
      "Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from selenium) (1.26.20)\n",
      "Requirement already satisfied: certifi>=2021.10.8 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from selenium) (2025.10.5)\n",
      "Requirement already satisfied: websocket-client~=1.8 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from selenium) (1.8.0)\n",
      "Requirement already satisfied: trio-websocket~=0.9 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from selenium) (0.12.2)\n",
      "Requirement already satisfied: idna in c:\\users\\skand\\anaconda3\\lib\\site-packages (from trio~=0.17->selenium) (2.10)\n",
      "Requirement already satisfied: sniffio>=1.3.0 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from trio~=0.17->selenium) (1.3.1)\n",
      "Requirement already satisfied: exceptiongroup; python_version < \"3.11\" in c:\\users\\skand\\anaconda3\\lib\\site-packages (from trio~=0.17->selenium) (1.3.0)\n",
      "Requirement already satisfied: attrs>=23.2.0 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from trio~=0.17->selenium) (25.3.0)\n",
      "Requirement already satisfied: cffi>=1.14; os_name == \"nt\" and implementation_name != \"pypy\" in c:\\users\\skand\\anaconda3\\lib\\site-packages (from trio~=0.17->selenium) (1.14.3)\n",
      "Requirement already satisfied: outcome in c:\\users\\skand\\anaconda3\\lib\\site-packages (from trio~=0.17->selenium) (1.3.0.post0)\n",
      "Requirement already satisfied: sortedcontainers in c:\\users\\skand\\anaconda3\\lib\\site-packages (from trio~=0.17->selenium) (2.2.2)\n",
      "Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6; extra == \"socks\" in c:\\users\\skand\\anaconda3\\lib\\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)\n",
      "Requirement already satisfied: wsproto>=0.14 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)\n",
      "Requirement already satisfied: pycparser in c:\\users\\skand\\anaconda3\\lib\\site-packages (from cffi>=1.14; os_name == \"nt\" and implementation_name != \"pypy\"->trio~=0.17->selenium) (2.20)\n",
      "Requirement already satisfied: h11<1,>=0.9.0 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install selenium "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting webdriver-manager\n",
      "  Downloading webdriver_manager-4.1.2-py3-none-any.whl (32 kB)\n",
      "Requirement already satisfied: requests in c:\\users\\skand\\anaconda3\\lib\\site-packages (from webdriver-manager) (2.32.4)\n",
      "Collecting python-dotenv\n",
      "  Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)\n",
      "Requirement already satisfied: packaging in c:\\users\\skand\\anaconda3\\lib\\site-packages (from webdriver-manager) (24.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from requests->webdriver-manager) (2.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from requests->webdriver-manager) (1.26.20)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from requests->webdriver-manager) (3.4.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\skand\\anaconda3\\lib\\site-packages (from requests->webdriver-manager) (2025.10.5)\n",
      "Installing collected packages: python-dotenv, webdriver-manager\n",
      "Successfully installed python-dotenv-1.0.1 webdriver-manager-4.1.2\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install webdriver-manager"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Nombre de liens récupérés : 10\n",
      "Nombre d'annonces extraites : 10\n",
      "Temps total d'exécution : 54.197 secondes\n",
      "RAM utilisée : 3.99 MB\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Reference</th>\n",
       "      <th>Title</th>\n",
       "      <th>Price</th>\n",
       "      <th>Location</th>\n",
       "      <th>Surface</th>\n",
       "      <th>Description</th>\n",
       "      <th>Url_annonce</th>\n",
       "      <th>Execution_time_sec</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>8345220</td>\n",
       "      <td>Un appartement S3 à vendre à Ain Zaghouan Nord</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>136 m²</td>\n",
       "      <td>Agence Immobilière Le Carré 9 vous propose à l...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8345220/un-apparte...</td>\n",
       "      <td>3.149</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>8353116</td>\n",
       "      <td>S2 en vente</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>136 m²</td>\n",
       "      <td>Cet appartement situé dans une résidence élevé...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8353116/s2-en-vente</td>\n",
       "      <td>2.795</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>8333499</td>\n",
       "      <td>S4 en vente</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>150 m²</td>\n",
       "      <td>Cet appartement, idéalement situé au cœur d’Ai...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8333499/s4-en-vente</td>\n",
       "      <td>3.104</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>8336332</td>\n",
       "      <td>À Vendre S4 avec terrasse vue mer à AFH Mrezga</td>\n",
       "      <td></td>\n",
       "      <td>Cité El Wafa à Nabeul</td>\n",
       "      <td>238 m²</td>\n",
       "      <td>Cet appartement de 182m² avec une terrasse de ...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8336332/%C3%A0-ven...</td>\n",
       "      <td>3.420</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>8312183</td>\n",
       "      <td>A vendre s2 au lac 1</td>\n",
       "      <td></td>\n",
       "      <td>Les Berges Du Lac 1 à Tunis</td>\n",
       "      <td>90 m²</td>\n",
       "      <td>A vendre un appartement s2 dans une résidence ...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8312183/a-vendre-s...</td>\n",
       "      <td>3.029</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>8362013</td>\n",
       "      <td>À vendre S2 dans une résidence à cité el wafaN...</td>\n",
       "      <td></td>\n",
       "      <td>Cité El Wafa à Nabeul</td>\n",
       "      <td>98 m²</td>\n",
       "      <td>Cet appartement est situé dans une résidence r...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8362013/%C3%A0-ven...</td>\n",
       "      <td>3.258</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>8302856</td>\n",
       "      <td>Duplex en vente</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>160 m²</td>\n",
       "      <td>Ce duplex en s3 s'étend sur le rez-de-chaussée...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8302856/duplex-en-...</td>\n",
       "      <td>3.177</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>8353111</td>\n",
       "      <td>S1 en vente</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>61 m²</td>\n",
       "      <td>Cet appartement situé dans une résidence élevé...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8353111/s1-en-vente</td>\n",
       "      <td>3.248</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>8298737</td>\n",
       "      <td>S3 en vente</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>207 m²</td>\n",
       "      <td>Cet appartement est situé dans une résidence r...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8298737/s3-en-vente</td>\n",
       "      <td>3.467</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>8355641</td>\n",
       "      <td>S2 en vente</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>116 m²</td>\n",
       "      <td>Cet appartement se situe ç ain zaghouen , offr...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8355641/s2-en-vente</td>\n",
       "      <td>2.749</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Reference                                              Title Price  \\\n",
       "0   8345220     Un appartement S3 à vendre à Ain Zaghouan Nord         \n",
       "1   8353116                                        S2 en vente         \n",
       "2   8333499                                        S4 en vente         \n",
       "3   8336332     À Vendre S4 avec terrasse vue mer à AFH Mrezga         \n",
       "4   8312183                               A vendre s2 au lac 1         \n",
       "5   8362013  À vendre S2 dans une résidence à cité el wafaN...         \n",
       "6   8302856                                    Duplex en vente         \n",
       "7   8353111                                        S1 en vente         \n",
       "8   8298737                                        S3 en vente         \n",
       "9   8355641                                        S2 en vente         \n",
       "\n",
       "                       Location Surface  \\\n",
       "0  Ain Zaghouan Nord à La Marsa  136 m²   \n",
       "1  Ain Zaghouan Nord à La Marsa  136 m²   \n",
       "2  Ain Zaghouan Nord à La Marsa  150 m²   \n",
       "3         Cité El Wafa à Nabeul  238 m²   \n",
       "4   Les Berges Du Lac 1 à Tunis   90 m²   \n",
       "5         Cité El Wafa à Nabeul   98 m²   \n",
       "6  Ain Zaghouan Nord à La Marsa  160 m²   \n",
       "7  Ain Zaghouan Nord à La Marsa   61 m²   \n",
       "8  Ain Zaghouan Nord à La Marsa  207 m²   \n",
       "9  Ain Zaghouan Nord à La Marsa  116 m²   \n",
       "\n",
       "                                         Description  \\\n",
       "0  Agence Immobilière Le Carré 9 vous propose à l...   \n",
       "1  Cet appartement situé dans une résidence élevé...   \n",
       "2  Cet appartement, idéalement situé au cœur d’Ai...   \n",
       "3  Cet appartement de 182m² avec une terrasse de ...   \n",
       "4  A vendre un appartement s2 dans une résidence ...   \n",
       "5  Cet appartement est situé dans une résidence r...   \n",
       "6  Ce duplex en s3 s'étend sur le rez-de-chaussée...   \n",
       "7  Cet appartement situé dans une résidence élevé...   \n",
       "8  Cet appartement est situé dans une résidence r...   \n",
       "9  Cet appartement se situe ç ain zaghouen , offr...   \n",
       "\n",
       "                                         Url_annonce  Execution_time_sec  \n",
       "0  https://www.mubawab.tn/fr/a/8345220/un-apparte...               3.149  \n",
       "1    https://www.mubawab.tn/fr/a/8353116/s2-en-vente               2.795  \n",
       "2    https://www.mubawab.tn/fr/a/8333499/s4-en-vente               3.104  \n",
       "3  https://www.mubawab.tn/fr/a/8336332/%C3%A0-ven...               3.420  \n",
       "4  https://www.mubawab.tn/fr/a/8312183/a-vendre-s...               3.029  \n",
       "5  https://www.mubawab.tn/fr/a/8362013/%C3%A0-ven...               3.258  \n",
       "6  https://www.mubawab.tn/fr/a/8302856/duplex-en-...               3.177  \n",
       "7    https://www.mubawab.tn/fr/a/8353111/s1-en-vente               3.248  \n",
       "8    https://www.mubawab.tn/fr/a/8298737/s3-en-vente               3.467  \n",
       "9    https://www.mubawab.tn/fr/a/8355641/s2-en-vente               2.749  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import time\n",
    "import re\n",
    "import os\n",
    "import psutil\n",
    "import pandas as pd\n",
    "\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "\n",
    "\n",
    "LIST_URL = \"https://www.mubawab.tn/fr/sc/appartements-a-vendre\"\n",
    "\n",
    "\n",
    "def clean_text(text):\n",
    "    if text is None:\n",
    "        return None\n",
    "\n",
    "    text = re.sub(r\"\\s+\", \" \", text)\n",
    "    return text.strip()\n",
    "\n",
    "\n",
    "def extract_reference(url):\n",
    "    match = re.search(r\"/a/(\\d+)/\", url)\n",
    "    return match.group(1) if match else None\n",
    "\n",
    "\n",
    "def extract_surface(text):\n",
    "    match = re.search(r\"(\\d+(?:[.,]\\d+)?)\\s*m²\", text)\n",
    "    return f\"{match.group(1)} m²\" if match else None\n",
    "\n",
    "\n",
    "def get_text_by_css(driver, selector):\n",
    "    try:\n",
    "        element = driver.find_element(By.CSS_SELECTOR, selector)\n",
    "        return clean_text(element.text)\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "\n",
    "def get_ad_links(driver, limit=10):\n",
    "    driver.get(LIST_URL)\n",
    "    time.sleep(3)\n",
    "\n",
    "    elements = driver.find_elements(By.CSS_SELECTOR, 'a[href*=\"/fr/a/\"]')\n",
    "\n",
    "    links = []\n",
    "\n",
    "    for element in elements:\n",
    "        href = element.get_attribute(\"href\")\n",
    "\n",
    "        if href and href not in links:\n",
    "            links.append(href)\n",
    "\n",
    "        if len(links) >= limit:\n",
    "            break\n",
    "\n",
    "    return links\n",
    "\n",
    "\n",
    "def extract_description(driver, title):\n",
    "    description = get_text_by_css(driver, \".blockProp\")\n",
    "\n",
    "    if description and title:\n",
    "        description = description.replace(title, \"\", 1).strip()\n",
    "\n",
    "    return description\n",
    "\n",
    "\n",
    "def extract_mubawab_ad(driver, url):\n",
    "    start = time.time()\n",
    "\n",
    "    driver.get(url)\n",
    "    time.sleep(2)\n",
    "\n",
    "    page_text = clean_text(driver.find_element(By.TAG_NAME, \"body\").text)\n",
    "\n",
    "    title = get_text_by_css(driver, \"h1\")\n",
    "    price = get_text_by_css(driver, \".fullPicturesPrice\")\n",
    "    location = get_text_by_css(driver, \".greyTit\")\n",
    "    surface = extract_surface(page_text)\n",
    "    description = extract_description(driver, title)\n",
    "\n",
    "    return {\n",
    "        \"Reference\": extract_reference(url),\n",
    "        \"Title\": title,\n",
    "        \"Price\": price,\n",
    "        \"Location\": location,\n",
    "        \"Surface\": surface,\n",
    "        \"Description\": description,\n",
    "        \"Url_annonce\": url,\n",
    "        \"Execution_time_sec\": round(time.time() - start, 3),\n",
    "    }\n",
    "\n",
    "\n",
    "def create_driver():\n",
    "    options = Options()\n",
    "    options.add_argument(\"--headless=new\")\n",
    "    options.add_argument(\"--disable-gpu\")\n",
    "    options.add_argument(\"--window-size=1920,1080\")\n",
    "    options.add_argument(\"--log-level=3\")\n",
    "\n",
    "    driver = webdriver.Chrome(\n",
    "        service=Service(ChromeDriverManager().install()),\n",
    "        options=options\n",
    "    )\n",
    "\n",
    "    return driver\n",
    "\n",
    "\n",
    "def scrape_mubawab_first_page_selenium(limit=10):\n",
    "    process = psutil.Process(os.getpid())\n",
    "    ram_before = process.memory_info().rss / 1024 / 1024\n",
    "\n",
    "    start = time.time()\n",
    "\n",
    "    driver = create_driver()\n",
    "\n",
    "    try:\n",
    "        links = get_ad_links(driver, limit=limit)\n",
    "\n",
    "        results = []\n",
    "\n",
    "        for link in links:\n",
    "            result = extract_mubawab_ad(driver, link)\n",
    "            results.append(result)\n",
    "\n",
    "        df = pd.DataFrame(results)\n",
    "\n",
    "    finally:\n",
    "        driver.quit()\n",
    "\n",
    "    total_time = round(time.time() - start, 3)\n",
    "\n",
    "    ram_after = process.memory_info().rss / 1024 / 1024\n",
    "    ram_used = ram_after - ram_before\n",
    "\n",
    "    print(f\"Nombre de liens récupérés : {len(links)}\")\n",
    "    print(f\"Nombre d'annonces extraites : {len(df)}\")\n",
    "    print(f\"Temps total d'exécution : {total_time} secondes\")\n",
    "    print(f\"RAM utilisée : {ram_used:.2f} MB\")\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "df = scrape_mubawab_first_page_selenium(limit=10)\n",
    "\n",
    "display(df)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Nombre de liens récupérés : 10\n",
      "Nombre d'annonces extraites : 10\n",
      "Temps total d'exécution : 41.226 secondes\n",
      "RAM utilisée : 554.68 MB\n",
      "RAM totale mesurée avant fermeture de Chrome : 968.57 MB\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Reference</th>\n",
       "      <th>Title</th>\n",
       "      <th>Price</th>\n",
       "      <th>Location</th>\n",
       "      <th>Surface</th>\n",
       "      <th>Description</th>\n",
       "      <th>Url_annonce</th>\n",
       "      <th>Execution_time_sec</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>8345220</td>\n",
       "      <td>Un appartement S3 à vendre à Ain Zaghouan Nord</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>136 m²</td>\n",
       "      <td>Agence Immobilière Le Carré 9 vous propose à l...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8345220/un-apparte...</td>\n",
       "      <td>3.150</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>8353116</td>\n",
       "      <td>S2 en vente</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>136 m²</td>\n",
       "      <td>Cet appartement situé dans une résidence élevé...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8353116/s2-en-vente</td>\n",
       "      <td>2.677</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>8333499</td>\n",
       "      <td>S4 en vente</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>150 m²</td>\n",
       "      <td>Cet appartement, idéalement situé au cœur d’Ai...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8333499/s4-en-vente</td>\n",
       "      <td>3.262</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>8336332</td>\n",
       "      <td>À Vendre S4 avec terrasse vue mer à AFH Mrezga</td>\n",
       "      <td></td>\n",
       "      <td>Cité El Wafa à Nabeul</td>\n",
       "      <td>238 m²</td>\n",
       "      <td>Cet appartement de 182m² avec une terrasse de ...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8336332/%C3%A0-ven...</td>\n",
       "      <td>3.206</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>8312183</td>\n",
       "      <td>A vendre s2 au lac 1</td>\n",
       "      <td></td>\n",
       "      <td>Les Berges Du Lac 1 à Tunis</td>\n",
       "      <td>90 m²</td>\n",
       "      <td>A vendre un appartement s2 dans une résidence ...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8312183/a-vendre-s...</td>\n",
       "      <td>2.788</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>8361105</td>\n",
       "      <td>À vendre – Appartement S3 à L’Aouina</td>\n",
       "      <td></td>\n",
       "      <td>El Aouina à Tunis</td>\n",
       "      <td>170 m²</td>\n",
       "      <td>À vendre – Appartement S3 à L’Aouina cité les ...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8361105/%C3%A0-ven...</td>\n",
       "      <td>3.112</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>8354741</td>\n",
       "      <td>A vendre appartement S3 cité ennasr 2</td>\n",
       "      <td></td>\n",
       "      <td>Cité Ennasr 2 à Ariana</td>\n",
       "      <td>95 m²</td>\n",
       "      <td>Appartement S3 à vendre – Cité Ennasr 2 Découv...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8354741/a-vendre-a...</td>\n",
       "      <td>2.982</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>8312780</td>\n",
       "      <td>À vendre S1 dans une résidence à AFH Mrezga</td>\n",
       "      <td></td>\n",
       "      <td>Cité El Wafa à Nabeul</td>\n",
       "      <td>64 m²</td>\n",
       "      <td>Cet appartement est situé dans une résidence r...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8312780/%C3%A0-ven...</td>\n",
       "      <td>2.932</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>8362013</td>\n",
       "      <td>À vendre S2 dans une résidence à cité el wafaN...</td>\n",
       "      <td></td>\n",
       "      <td>Cité El Wafa à Nabeul</td>\n",
       "      <td>98 m²</td>\n",
       "      <td>Cet appartement est situé dans une résidence r...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8362013/%C3%A0-ven...</td>\n",
       "      <td>4.151</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>8302856</td>\n",
       "      <td>Duplex en vente</td>\n",
       "      <td></td>\n",
       "      <td>Ain Zaghouan Nord à La Marsa</td>\n",
       "      <td>160 m²</td>\n",
       "      <td>Ce duplex en s3 s'étend sur le rez-de-chaussée...</td>\n",
       "      <td>https://www.mubawab.tn/fr/a/8302856/duplex-en-...</td>\n",
       "      <td>2.893</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Reference                                              Title Price  \\\n",
       "0   8345220     Un appartement S3 à vendre à Ain Zaghouan Nord         \n",
       "1   8353116                                        S2 en vente         \n",
       "2   8333499                                        S4 en vente         \n",
       "3   8336332     À Vendre S4 avec terrasse vue mer à AFH Mrezga         \n",
       "4   8312183                               A vendre s2 au lac 1         \n",
       "5   8361105               À vendre – Appartement S3 à L’Aouina         \n",
       "6   8354741              A vendre appartement S3 cité ennasr 2         \n",
       "7   8312780        À vendre S1 dans une résidence à AFH Mrezga         \n",
       "8   8362013  À vendre S2 dans une résidence à cité el wafaN...         \n",
       "9   8302856                                    Duplex en vente         \n",
       "\n",
       "                       Location Surface  \\\n",
       "0  Ain Zaghouan Nord à La Marsa  136 m²   \n",
       "1  Ain Zaghouan Nord à La Marsa  136 m²   \n",
       "2  Ain Zaghouan Nord à La Marsa  150 m²   \n",
       "3         Cité El Wafa à Nabeul  238 m²   \n",
       "4   Les Berges Du Lac 1 à Tunis   90 m²   \n",
       "5             El Aouina à Tunis  170 m²   \n",
       "6        Cité Ennasr 2 à Ariana   95 m²   \n",
       "7         Cité El Wafa à Nabeul   64 m²   \n",
       "8         Cité El Wafa à Nabeul   98 m²   \n",
       "9  Ain Zaghouan Nord à La Marsa  160 m²   \n",
       "\n",
       "                                         Description  \\\n",
       "0  Agence Immobilière Le Carré 9 vous propose à l...   \n",
       "1  Cet appartement situé dans une résidence élevé...   \n",
       "2  Cet appartement, idéalement situé au cœur d’Ai...   \n",
       "3  Cet appartement de 182m² avec une terrasse de ...   \n",
       "4  A vendre un appartement s2 dans une résidence ...   \n",
       "5  À vendre – Appartement S3 à L’Aouina cité les ...   \n",
       "6  Appartement S3 à vendre – Cité Ennasr 2 Découv...   \n",
       "7  Cet appartement est situé dans une résidence r...   \n",
       "8  Cet appartement est situé dans une résidence r...   \n",
       "9  Ce duplex en s3 s'étend sur le rez-de-chaussée...   \n",
       "\n",
       "                                         Url_annonce  Execution_time_sec  \n",
       "0  https://www.mubawab.tn/fr/a/8345220/un-apparte...               3.150  \n",
       "1    https://www.mubawab.tn/fr/a/8353116/s2-en-vente               2.677  \n",
       "2    https://www.mubawab.tn/fr/a/8333499/s4-en-vente               3.262  \n",
       "3  https://www.mubawab.tn/fr/a/8336332/%C3%A0-ven...               3.206  \n",
       "4  https://www.mubawab.tn/fr/a/8312183/a-vendre-s...               2.788  \n",
       "5  https://www.mubawab.tn/fr/a/8361105/%C3%A0-ven...               3.112  \n",
       "6  https://www.mubawab.tn/fr/a/8354741/a-vendre-a...               2.982  \n",
       "7  https://www.mubawab.tn/fr/a/8312780/%C3%A0-ven...               2.932  \n",
       "8  https://www.mubawab.tn/fr/a/8362013/%C3%A0-ven...               4.151  \n",
       "9  https://www.mubawab.tn/fr/a/8302856/duplex-en-...               2.893  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import time\n",
    "import re\n",
    "import os\n",
    "import psutil\n",
    "import pandas as pd\n",
    "\n",
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.service import Service\n",
    "from selenium.webdriver.common.by import By\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from webdriver_manager.chrome import ChromeDriverManager\n",
    "\n",
    "\n",
    "LIST_URL = \"https://www.mubawab.tn/fr/sc/appartements-a-vendre\"\n",
    "\n",
    "\n",
    "def clean_text(text):\n",
    "    if text is None:\n",
    "        return None\n",
    "\n",
    "    text = re.sub(r\"\\s+\", \" \", text)\n",
    "    return text.strip()\n",
    "\n",
    "\n",
    "def extract_reference(url):\n",
    "    match = re.search(r\"/a/(\\d+)/\", url)\n",
    "    return match.group(1) if match else None\n",
    "\n",
    "\n",
    "def extract_surface(text):\n",
    "    match = re.search(r\"(\\d+(?:[.,]\\d+)?)\\s*m²\", text)\n",
    "    return f\"{match.group(1)} m²\" if match else None\n",
    "\n",
    "\n",
    "def get_text_by_css(driver, selector):\n",
    "    try:\n",
    "        element = driver.find_element(By.CSS_SELECTOR, selector)\n",
    "        return clean_text(element.text)\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "\n",
    "def get_process_memory_mb(process):\n",
    "    total_memory = 0\n",
    "\n",
    "    try:\n",
    "        total_memory += process.memory_info().rss\n",
    "\n",
    "        for child in process.children(recursive=True):\n",
    "            try:\n",
    "                total_memory += child.memory_info().rss\n",
    "            except psutil.NoSuchProcess:\n",
    "                pass\n",
    "\n",
    "    except psutil.NoSuchProcess:\n",
    "        pass\n",
    "\n",
    "    return total_memory / 1024 / 1024\n",
    "\n",
    "\n",
    "def create_driver():\n",
    "    options = Options()\n",
    "    options.add_argument(\"--headless=new\")\n",
    "    options.add_argument(\"--disable-gpu\")\n",
    "    options.add_argument(\"--window-size=1920,1080\")\n",
    "    options.add_argument(\"--log-level=3\")\n",
    "\n",
    "    driver = webdriver.Chrome(\n",
    "        service=Service(ChromeDriverManager().install()),\n",
    "        options=options\n",
    "    )\n",
    "\n",
    "    return driver\n",
    "\n",
    "\n",
    "def get_ad_links(driver, limit=10):\n",
    "    driver.get(LIST_URL)\n",
    "    time.sleep(3)\n",
    "\n",
    "    elements = driver.find_elements(By.CSS_SELECTOR, 'a[href*=\"/fr/a/\"]')\n",
    "\n",
    "    links = []\n",
    "\n",
    "    for element in elements:\n",
    "        href = element.get_attribute(\"href\")\n",
    "\n",
    "        if href and href not in links:\n",
    "            links.append(href)\n",
    "\n",
    "        if len(links) >= limit:\n",
    "            break\n",
    "\n",
    "    return links\n",
    "\n",
    "\n",
    "def extract_description(driver, title):\n",
    "    description = get_text_by_css(driver, \".blockProp\")\n",
    "\n",
    "    if description and title:\n",
    "        description = description.replace(title, \"\", 1).strip()\n",
    "\n",
    "    return description\n",
    "\n",
    "\n",
    "def extract_mubawab_ad(driver, url):\n",
    "    start = time.time()\n",
    "\n",
    "    driver.get(url)\n",
    "    time.sleep(2)\n",
    "\n",
    "    page_text = clean_text(driver.find_element(By.TAG_NAME, \"body\").text)\n",
    "\n",
    "    title = get_text_by_css(driver, \"h1\")\n",
    "    price = get_text_by_css(driver, \".fullPicturesPrice\")\n",
    "    location = get_text_by_css(driver, \".greyTit\")\n",
    "    surface = extract_surface(page_text)\n",
    "    description = extract_description(driver, title)\n",
    "\n",
    "    return {\n",
    "        \"Reference\": extract_reference(url),\n",
    "        \"Title\": title,\n",
    "        \"Price\": price,\n",
    "        \"Location\": location,\n",
    "        \"Surface\": surface,\n",
    "        \"Description\": description,\n",
    "        \"Url_annonce\": url,\n",
    "        \"Execution_time_sec\": round(time.time() - start, 3),\n",
    "    }\n",
    "\n",
    "\n",
    "def scrape_mubawab_first_page_selenium(limit=10):\n",
    "    parent_process = psutil.Process(os.getpid())\n",
    "\n",
    "    start = time.time()\n",
    "\n",
    "    driver = create_driver()\n",
    "\n",
    "    ram_before = get_process_memory_mb(parent_process)\n",
    "\n",
    "    try:\n",
    "        links = get_ad_links(driver, limit=limit)\n",
    "\n",
    "        results = []\n",
    "\n",
    "        for link in links:\n",
    "            result = extract_mubawab_ad(driver, link)\n",
    "            results.append(result)\n",
    "\n",
    "        df = pd.DataFrame(results)\n",
    "\n",
    "        ram_after = get_process_memory_mb(parent_process)\n",
    "\n",
    "    finally:\n",
    "        driver.quit()\n",
    "\n",
    "    total_time = round(time.time() - start, 3)\n",
    "    ram_used = ram_after - ram_before\n",
    "\n",
    "    print(f\"Nombre de liens récupérés : {len(links)}\")\n",
    "    print(f\"Nombre d'annonces extraites : {len(df)}\")\n",
    "    print(f\"Temps total d'exécution : {total_time} secondes\")\n",
    "    print(f\"RAM utilisée : {ram_used:.2f} MB\")\n",
    "    print(f\"RAM totale mesurée avant fermeture de Chrome : {ram_after:.2f} MB\")\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "df = scrape_mubawab_first_page_selenium(limit=10)\n",
    "\n",
    "display(df)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
